config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :contacts do
    resources :notes
  end
  root 'welcome#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	has_many :notes, dependent: :destroy
	validates :name, presence: true, length: {minimum: 5}
	validates :phone, presence: true, length: {minimum: 8}
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    @contacts = Contact.all
  end
	
	def new
    @contact = Contact.new
	end

	def show
		@contact = Contact.find(params[:id])
	end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    redirect_to contacts_path
  end

	def create
		@contact = Contact.new(contact_params)

  	if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
	end

	private
		def contact_params
			params.require(:contact).permit(:name, :phone, :email, :adress)
		end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def create
	    @contact = Contact.find(params[:contact_id])
	    @note = @contact.notes.create(note_params)
	    redirect_to contact_path(@contact)
  	end

  def destroy
    @contact =Contact.find(params[:contact_id])
    @note = @contact.notes.find(params[:id])
    @note.destroy
    redirect_to contact_path(@contact)
  end
 
  private
    def note_params
      params.require(:note).permit(:text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<div class="col-md-4 col-md-offset-5">
  <%= form_for @contact do |f| %> 
    <% if @contact.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@contact.errors.count, "error") %> prohibited
          this contact from being saved:</h2>
        <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %> 
    <p>
      <%= f.label :nome %><br>
      <%= f.text_field :name %>
    </p>
   
    <p>
      <%= f.label :telefone %><br>
      <%= f.text_field :phone %>
    </p>

    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email %> (opcional)
    </p>

    <p>
      <%= f.label :endereço %><br>
      <%= f.text_field :adress %> (opcional)
    </p>
   
    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/contacts/edit.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<h1 class="text-center">Editar contato</h1>
 
<%= render 'form' %>
 
<div class="col-md-2 col-md-offset-5">
  <button type="button" class="btn btn-default btn-lg btn-block">
  		<span class="glyphicon glyphicon-circle-arrow-left"></span>
		<%= link_to 'Voltar', contacts_path %>
	</button>
</div>

app/views/contacts/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<h1 class="text-center">Contatos</h1>

<div class="col-md-4 col-md-offset-4">
  <table class="table table-bordered">
    <tr>
      <th>#ID</th>
      <th>Nome</th>
    </tr>
   
    <% @contacts.each do |contact| %>
      <tr>
        <td>#<%= contact.id %></td>
        <td><%= link_to contact.name, contact_path(contact) %></td>
      </tr>
    <% end %>
  </table>
</div>

</p>
<div class="col-md-4 col-md-offset-4">
  <button type="button" class="btn btn-default btn-lg btn-block">
    <span class="glyphicon glyphicon-user"></span>
    <%= link_to 'Novo Contato', new_contact_path %>
  </button>
  <button type="button" class="btn btn-default btn-lg btn-block">
    <span class="glyphicon glyphicon-home"></span>
    <%= link_to 'Home', controller: 'welcome' %>
  </button>
</div>

app/views/contacts/new.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<h1 class="text-center">Novo Contato</h1>

<%= render 'form' %>

<div class="col-md-2 col-md-offset-5">
  <button type="button" class="btn btn-default btn-lg btn-block">
  		<span class="glyphicon glyphicon-circle-arrow-left"></span>
		<%= link_to 'Voltar', contacts_path %>
	</button>
</div>

app/views/contacts/show.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<h1 class="text-center"><%= @contact.name %> </h1>

<div class="col-md-4 col-md-offset-5">
	</p>
	<strong>Telefone:</strong>
	<%= @contact.phone %></br>

	<strong>E-mail:</strong>
	<%= @contact.email %></br>

	<strong>Endereco:</strong>
	<%= @contact.adress %></br>
	<button type="button" class="btn btn-default btn-lg btn-sm">
		<span class="glyphicon glyphicon-edit"></span>
		<%= link_to 'Editar', edit_contact_path(@contact) %> 
	</button>
	<button type="button" class="btn btn-default btn-lg btn-sm">
		<span class="glyphicon glyphicon-remove"></span>
		<%= link_to 'Deletar', contact_path(@contact), method: :delete, data: { confirm: 'Tem certeza?' } %></br>
	</button>
	<h2>Notas</h2>
	<%= render @contact.notes %>

	<h2>Adcionar nota:</h2>
	<%= render "notes/form" %>
</div>

<div class="col-md-2 col-md-offset-5">
  <button type="button" class="btn btn-default btn-lg btn-block">
  		<span class="glyphicon glyphicon-circle-arrow-left"></span>
		<%= link_to 'Voltar', contacts_path %>
	</button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogAgenda4soft</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for([@contact, @contact.notes.build]) do |f| %>
  <%= f.text_area :text %><br>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/notes/_note.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
</p>
  <strong>Nota #<%= note.id%>:</strong>
  <%= note.text %><br>
  <button type="button" class="btn btn-default btn-lg btn-sm">
  	<span class="glyphicon glyphicon-remove"></span>
  	<%= link_to 'Excluir Nota', [note.contact, note], method: :delete, data: { confirm: 'Tem certeza?' } %>
  </button>
</p>

app/views/welcome/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<div class="col-md-4 col-md-offset-4">
	<h1 class="text-center">BlogAgenda</h1>
	<p class="text-center">Mantenha seus contatos salvos, tudo online!</p>
</div>

<div class="col-md-2 col-md-offset-5">
	<button type="button" class="btn btn-default btn-lg btn-block">
		<span class="glyphicon glyphicon-list-alt"></span>
		<%= link_to 'Agenda', controller: 'contacts' %>
	</button>
</div>